"""Lesson design agent.

Current stage: hybrid local Ollama + rule-based fallback.
Future replacement: the lesson design can be generated by Ollama / DeepSeek /
OpenAI while keeping the same output schema and fallback behavior.
"""

import json

from services.llm_service import call_agent_json, trim_knowledge_context_for_prompt
from services.knowledge_retrieval_service import format_knowledge_context_for_prompt
from services.mock_ai_service import normalize_lesson_type


def _topic_keyword(lesson_request):
    topic = lesson_request.get("topic") or "the topic"
    return topic.split()[-1].strip(".,!?") if topic.strip() else "the topic"


def _build_objectives(lesson_request):
    lesson_type = normalize_lesson_type(lesson_request.get("lesson_type"))
    keyword = _topic_keyword(lesson_request)

    objectives_map = {
        "reading": [
            f"Identify the main idea and key details related to {keyword}.",
            "Use reading evidence to answer guided classroom questions.",
            "Give a short spoken or written response with clear support.",
        ],
        "grammar": [
            "Notice the target grammar form and explain its basic use.",
            "Apply the grammar rule in guided and controlled practice.",
            "Produce one short output with the target structure accurately.",
        ],
        "writing": [
            "Understand the writing task, audience, and text purpose.",
            "Use useful expressions and a clear structure to build a draft.",
            "Complete a classroom writing product with teacher support.",
        ],
        "listening_speaking": [
            "Catch the gist and key details of the listening input.",
            "Use the listening material as support for spoken interaction.",
            "Deliver a short classroom speaking response with confidence.",
        ],
        "revision": [
            "Recall core unit knowledge efficiently and accurately.",
            "Connect vocabulary, grammar, and topic content in one task.",
            "Show transfer through a mixed-skill classroom review activity.",
        ],
    }
    return objectives_map.get(lesson_type, objectives_map["reading"])


def _build_key_points(lesson_request):
    lesson_type = normalize_lesson_type(lesson_request.get("lesson_type"))
    topic = lesson_request.get("topic") or "the lesson topic"

    key_point_map = {
        "reading": [
            f"Understand the central meaning of {topic}.",
            "Use textual evidence and useful expressions in discussion.",
            "Complete a reading-based output task with teamwork.",
        ],
        "grammar": [
            "Notice grammar form, meaning, and usage in context.",
            "Avoid common grammar mistakes through comparison and practice.",
            "Transfer the grammar item into meaningful classroom output.",
        ],
        "writing": [
            "Analyze the task clearly before drafting.",
            "Organize ideas with a suitable writing structure.",
            "Use practical expressions to improve classroom writing output.",
        ],
        "listening_speaking": [
            "Listen with a clear purpose for gist and detail.",
            "Use key words and expressions from the input for speaking.",
            "Encourage active oral participation in pair or group work.",
        ],
        "revision": [
            "Retrieve high-frequency unit knowledge quickly.",
            "Spot typical mistakes and correct them with reasons.",
            "Use reviewed knowledge in an integrated final task.",
        ],
    }
    return key_point_map.get(lesson_type, key_point_map["reading"])


def _build_difficult_points(lesson_request):
    student_level = lesson_request.get("student_level")
    level_support = {
        "基础薄弱": "Move from sentence frames to short independent answers.",
        "较好": "Use fuller evidence and more precise English in output.",
    }.get(student_level, "Move from guided understanding to independent use.")

    return [
        "Turn input understanding into spoken or written classroom output.",
        "Use target language accurately in meaningful contexts.",
        level_support,
    ]


def _build_teaching_methods(lesson_request):
    lesson_type = normalize_lesson_type(lesson_request.get("lesson_type"))
    methods = ["Task-based language teaching", "Scaffolded instruction"]

    if lesson_type == "reading":
        methods.append("Skimming and scanning training")
    elif lesson_type == "grammar":
        methods.append("Guided grammar discovery")
    elif lesson_type == "writing":
        methods.append("Model-based writing support")
    elif lesson_type == "listening_speaking":
        methods.append("Listening-to-speaking transfer")
    else:
        methods.append("Retrieval-based revision")

    if lesson_request.get("style") == "公开课":
        methods.append("Visible classroom interaction")

    return methods


def _build_flow_summary(lesson_request):
    lesson_type = normalize_lesson_type(lesson_request.get("lesson_type"))
    summaries = {
        "reading": "Lead-in, reading tasks, language support, discussion, summary, homework.",
        "grammar": "Observation, rule induction, guided practice, controlled practice, output, summary.",
        "writing": "Task analysis, language support, structure building, guided writing, review, homework.",
        "listening_speaking": "Pre-listening, while-listening, post-listening, speaking output, summary.",
        "revision": "Knowledge retrieval, focused review, integrated task, reflection, homework.",
    }
    return summaries.get(lesson_type, summaries["reading"])


def _build_rule_lesson_design(lesson_request):
    return {
        "teaching_objectives": _build_objectives(lesson_request),
        "key_points": _build_key_points(lesson_request),
        "difficult_points": _build_difficult_points(lesson_request),
        "teaching_methods": _build_teaching_methods(lesson_request),
        "lesson_flow_summary": _build_flow_summary(lesson_request),
    }


def generate_rule_lesson_design(lesson_request):
    """Return the local rule-based lesson design without any model call."""

    return _build_rule_lesson_design(lesson_request)


def _normalize_string_list(value, fallback):
    if isinstance(value, list):
        cleaned = [str(item).strip() for item in value if str(item or "").strip()]
        if cleaned:
            return cleaned[:4]
    return list(fallback)


def _normalize_lesson_design(payload, fallback):
    payload = payload if isinstance(payload, dict) else {}
    return {
        "teaching_objectives": _normalize_string_list(
            payload.get("teaching_objectives"),
            fallback["teaching_objectives"],
        ),
        "key_points": _normalize_string_list(
            payload.get("key_points"),
            fallback["key_points"],
        ),
        "difficult_points": _normalize_string_list(
            payload.get("difficult_points"),
            fallback["difficult_points"],
        ),
        "teaching_methods": _normalize_string_list(
            payload.get("teaching_methods"),
            fallback["teaching_methods"],
        ),
        "lesson_flow_summary": str(
            payload.get("lesson_flow_summary") or fallback["lesson_flow_summary"]
        ).strip(),
    }


def _knowledge_context_block(knowledge_context):
    if not knowledge_context:
        return ""
    return "\n\n" + trim_knowledge_context_for_prompt(format_knowledge_context_for_prompt(knowledge_context), max_chars=4000)


def _lesson_design_prompts(lesson_request, fallback, knowledge_context=None):
    system_prompt = """
You are a senior high school English teaching designer.
Return JSON only.
Write classroom content in natural, concise English suitable for Chinese senior high school learners.
"""
    user_prompt = f"""
Create a structured lesson design JSON for this lesson request.

Lesson request:
{json.dumps(lesson_request, ensure_ascii=False, indent=2)}

Fallback draft:
{json.dumps(fallback, ensure_ascii=False, indent=2)}

{_knowledge_context_block(knowledge_context)}

Return one JSON object with exactly these keys:
- teaching_objectives: array of 3 concise strings
- key_points: array of 3 concise strings
- difficult_points: array of 3 concise strings
- teaching_methods: array of 2 to 4 concise strings
- lesson_flow_summary: string

Requirements:
- Keep the content practical for a 45-minute senior high English lesson.
- Use English for the teaching design fields.
- Do not add markdown or explanations.
"""
    return system_prompt.strip(), user_prompt.strip()


def generate_lesson_design(lesson_request, knowledge_context=None):
    """Build a structured teaching design from the normalized request."""

    fallback = _build_rule_lesson_design(lesson_request)
    knowledge_context = knowledge_context or lesson_request.get("knowledge_context")
    system_prompt, user_prompt = _lesson_design_prompts(lesson_request, fallback, knowledge_context=knowledge_context)
    payload = call_agent_json(
        "lesson_design_agent",
        {
            "system_prompt": system_prompt,
            "user_prompt": user_prompt,
            "task_id": lesson_request.get("task_id"),
            "stage_note": "Generate structured lesson design.",
        },
        fallback_fn=lambda: fallback,
    )
    return _normalize_lesson_design(payload, fallback)
