"""Slide content generation agent.

Current stage: hybrid local Ollama + rule-based fallback.
Future replacement: each slide can be generated by a real model with context
from the lesson request, teaching design, and surrounding slides while
keeping the same fallback behavior.
"""

import json

from services.agents.json_schema_checker import check_schema
from services.llm_service import call_agent_json, trim_knowledge_context_for_prompt
from services.knowledge_retrieval_service import format_knowledge_context_for_prompt
from services.mock_ai_service import normalize_lesson_type


def _clean_lines(items, max_items=4):
    cleaned = [str(item).strip() for item in items if str(item or "").strip()]
    return cleaned[:max_items]


def _derive_context(lesson_request, teaching_design):
    topic = lesson_request.get("topic") or lesson_request.get("course_title") or "Senior English Lesson"
    topic_words = [word.strip(".,!?") for word in topic.split() if word.strip(".,!?")]
    keyword = topic_words[-1] if topic_words else "the topic"
    lesson_key = normalize_lesson_type(lesson_request.get("lesson_type"))

    lesson_labels = {
        "reading": "Reading and Thinking",
        "grammar": "Grammar Workshop",
        "writing": "Writing Workshop",
        "listening_speaking": "Listening and Speaking",
        "revision": "Revision Lesson",
    }
    output_labels = {
        "reading": "a short reading response",
        "grammar": "a short grammar-based response",
        "writing": "a guided writing draft",
        "listening_speaking": "a short spoken response",
        "revision": "a mixed review task",
    }
    vocabulary_sets = {
        "reading": ["main idea", "supporting detail", "text evidence"],
        "grammar": ["sentence pattern", "language form", "common mistake"],
        "writing": ["topic sentence", "supporting detail", "linking word"],
        "listening_speaking": ["key information", "useful expression", "spoken response"],
        "revision": ["key word", "grammar clue", "revision strategy"],
    }

    return {
        "topic": topic,
        "unit": lesson_request.get("unit") or "Unit 1",
        "grade": lesson_request.get("grade") or "高一",
        "textbook": lesson_request.get("textbook") or "人教版",
        "lesson_label": lesson_labels.get(lesson_key, "Senior English Lesson"),
        "lesson_key": lesson_key,
        "keyword": keyword,
        "output_label": output_labels.get(lesson_key, "a classroom task"),
        "vocabulary": vocabulary_sets.get(lesson_key, vocabulary_sets["reading"]),
        "objectives": teaching_design.get("teaching_objectives") or [],
        "key_points": teaching_design.get("key_points") or [],
        "difficult_points": teaching_design.get("difficult_points") or [],
        "teaching_methods": teaching_design.get("teaching_methods") or [],
        "extra_requirements": lesson_request.get("extra_requirements") or "",
    }


def _base_slide(lesson_request, slide_outline, teaching_design):
    context = _derive_context(lesson_request, teaching_design)
    return {
        "slide_index": slide_outline.get("slide_index"),
        "slide_type": slide_outline.get("slide_type"),
        "title": slide_outline.get("title") or "Untitled Slide",
        "visible_content": [],
        "teacher_notes": "",
        "teaching_purpose": slide_outline.get("teaching_purpose") or "",
        "estimated_time": slide_outline.get("estimated_time") or "3 minutes",
        "interaction_type": "Teacher-student interaction",
        "_context": context,
    }


def _cover_slide(slide):
    context = slide["_context"]
    slide["title"] = context["topic"]
    slide["visible_content"] = _clean_lines(
        [
            context["unit"],
            context["lesson_label"],
            f"{context['grade']} | {context['textbook']}",
        ],
        max_items=3,
    )
    slide["teacher_notes"] = (
        f"Welcome the class, introduce {context['topic']}, and make the lesson goal visible in one or two sentences."
    )
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _objectives_slide(slide):
    objectives = slide["_context"]["objectives"] or [
        "Understand the key learning goal of the lesson.",
        "Use lesson language to complete a classroom task.",
        "Show learning through a short response.",
    ]
    slide["visible_content"] = _clean_lines(objectives, max_items=3)
    slide["teacher_notes"] = "Read the objectives aloud and ask students which one may be the most challenging today."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _lead_in_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            f"Look at the topic: {context['topic']}.",
            f"Think: What do you already know about {context['keyword']}?",
            "Task: Share one idea with your partner.",
        ]
    )
    slide["teacher_notes"] = "Use a quick think-pair-share activity to activate prior knowledge without spending too much time."
    slide["interaction_type"] = "Pair work"
    return slide


def _prediction_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Read the title and key words.",
            "Predict what the text may talk about.",
            "Task: Write one guiding question before reading.",
        ]
    )
    slide["teacher_notes"] = "Collect two predictions and tell students to read with those predictions in mind."
    slide["interaction_type"] = "Individual work"
    return slide


def _fast_reading_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Read quickly for the main idea.",
            "Match each paragraph with one short heading.",
            "Task: Check your idea with a partner.",
        ]
    )
    slide["teacher_notes"] = "Time the reading tightly and remind students not to stop at every new word."
    slide["interaction_type"] = "Individual work"
    return slide


def _careful_reading_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Read again for key details.",
            "Answer the guided questions with evidence.",
            "Task: Underline the sentence that supports your answer.",
        ]
    )
    slide["teacher_notes"] = "Pause after each question and ask students where they found the answer in the text."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _vocabulary_focus_slide(slide):
    vocabulary = slide["_context"]["vocabulary"]
    slide["visible_content"] = _clean_lines(
        [
            f"Focus words: {vocabulary[0]}, {vocabulary[1]}, {vocabulary[2]}",
            "Match each word with its meaning or function.",
            "Task: Use one expression in a new sentence.",
        ]
    )
    slide["teacher_notes"] = "Keep vocabulary work brief and move students quickly into using the expressions in context."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _language_points_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            "Notice one useful sentence pattern from the text.",
            f"Try this frame: I think ... because ... about {context['keyword']}.",
            "Task: Complete the frame with your own idea.",
        ]
    )
    slide["teacher_notes"] = "Model the sentence pattern once, then let students produce one short example on their own."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _group_discussion_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            f"Question: What can we learn from {context['topic']}?",
            "Work in groups and prepare two key ideas.",
            "Task: Choose one speaker for the group report.",
        ]
    )
    slide["teacher_notes"] = "Circulate during the discussion and push students to support their ideas with reasons or examples."
    slide["interaction_type"] = "Group discussion"
    return slide


def _observe_discover_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Read the example sentences carefully.",
            "Underline the target pattern.",
            "Task: Discuss what changes in form and meaning.",
        ]
    )
    slide["teacher_notes"] = "Do not explain the rule too early; let students notice the form first."
    slide["interaction_type"] = "Pair work"
    return slide


def _grammar_rule_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Form: Find the grammar pattern.",
            "Meaning: Say when we use it.",
            "Task: Copy one model sentence and explain it.",
        ]
    )
    slide["teacher_notes"] = "Keep the explanation short and always connect the rule to one clear model sentence."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _guided_practice_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Complete the sentence frames.",
            "Use the target structure correctly.",
            "Task: Check your answers with a partner.",
        ]
    )
    slide["teacher_notes"] = "Give immediate support on the first two items so students feel secure before independent work."
    slide["interaction_type"] = "Pair work"
    return slide


def _controlled_practice_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Rewrite the sentences with the target form.",
            "Look for accuracy, not speed.",
            "Task: Correct one answer on the board together.",
        ]
    )
    slide["teacher_notes"] = "Use this stage to fix common errors before students move to freer language use."
    slide["interaction_type"] = "Individual work"
    return slide


def _communicative_practice_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            f"Use the grammar in a short dialogue about {context['keyword']}.",
            "Speak with a partner and use the target structure at least twice.",
            "Task: Share one example with the class.",
        ]
    )
    slide["teacher_notes"] = "Focus on communication first, then briefly correct the target grammar in shared answers."
    slide["interaction_type"] = "Pair work"
    return slide


def _error_correction_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Read the sentences with mistakes.",
            "Find the error and explain the reason.",
            "Task: Correct one sentence together.",
        ]
    )
    slide["teacher_notes"] = "Invite students to explain why an answer is wrong, not only what the correct answer is."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _writing_task_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            f"Writing goal: produce {context['output_label']}.",
            "Read the task and identify the audience and purpose.",
            "Task: Underline the key words in the prompt.",
        ]
    )
    slide["teacher_notes"] = "Make sure students know exactly what product they need to finish before drafting begins."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _structure_analysis_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Plan a clear beginning, body, and ending.",
            "Decide what idea belongs in each part.",
            "Task: Build a quick outline before writing.",
        ]
    )
    slide["teacher_notes"] = "Show a simple structure on the screen and let students build their own outline from it."
    slide["interaction_type"] = "Individual work"
    return slide


def _useful_expressions_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Use sentence starters for your opening.",
            "Add linking words such as first, besides, and finally.",
            "Task: Choose two expressions you will use today.",
        ]
    )
    slide["teacher_notes"] = "Keep the language practical and ask students to use the expressions in their own draft immediately."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _sample_analysis_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Read the model writing quickly.",
            "Find one strong idea and one useful expression.",
            "Task: Tell your partner what you can borrow from the sample.",
        ]
    )
    slide["teacher_notes"] = "Avoid over-explaining the sample; focus students on useful moves they can transfer."
    slide["interaction_type"] = "Pair work"
    return slide


def _guided_writing_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Write your first draft with the outline.",
            "Use at least two expressions from this lesson.",
            "Task: Finish one complete paragraph in class.",
        ]
    )
    slide["teacher_notes"] = "Walk around while students write and give quick support on organization before language accuracy."
    slide["interaction_type"] = "Individual work"
    return slide


def _peer_review_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Exchange your writing with a partner.",
            "Check content, structure, and useful language.",
            "Task: Give one praise and one suggestion.",
        ]
    )
    slide["teacher_notes"] = "Provide a short checklist so peer review stays simple and useful."
    slide["interaction_type"] = "Pair work"
    return slide


def _pre_listening_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Look at the topic and key words.",
            "Predict who is speaking and what may happen.",
            "Task: Set one question for the first listening.",
        ]
    )
    slide["teacher_notes"] = "Keep pre-listening short so students stay focused on the listening purpose."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _while_listening_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Listen once for the main idea.",
            "Listen again for key details.",
            "Task: Complete the note chart while listening.",
        ]
    )
    slide["teacher_notes"] = "Separate gist and detail listening so students are not overloaded by too many demands at once."
    slide["interaction_type"] = "Individual work"
    return slide


def _post_listening_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Check the answers with your partner.",
            "Retell the key message in two or three sentences.",
            "Task: Explain one detail that supports the message.",
        ]
    )
    slide["teacher_notes"] = "Move quickly from answer checking into meaning making and simple oral output."
    slide["interaction_type"] = "Pair work"
    return slide


def _speaking_task_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            f"Use the listening input to give {context['output_label']}.",
            "Include one opinion and one supporting reason.",
            "Task: Practice before sharing.",
        ]
    )
    slide["teacher_notes"] = "Give sentence starters to weaker students so everyone can produce a short spoken response."
    slide["interaction_type"] = "Pair work"
    return slide


def _pair_work_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Work with your partner.",
            "Ask and answer the guiding question.",
            "Task: Prepare one short report for the class.",
        ]
    )
    slide["teacher_notes"] = "Monitor the pair work and encourage balanced participation from both students."
    slide["interaction_type"] = "Pair work"
    return slide


def _key_vocabulary_review_slide(slide):
    vocabulary = slide["_context"]["vocabulary"]
    slide["visible_content"] = _clean_lines(
        [
            f"Review these key items: {vocabulary[0]}, {vocabulary[1]}, {vocabulary[2]}",
            "Match words with meanings or examples.",
            "Task: Use one item in a new sentence.",
        ]
    )
    slide["teacher_notes"] = "Use quick retrieval rather than long explanation so revision stays active."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _key_grammar_review_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Recall the unit grammar rule.",
            "Look at one model sentence and one common mistake.",
            "Task: Explain the correct form in simple English.",
        ]
    )
    slide["teacher_notes"] = "Focus only on the most useful rule and its common errors."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _exercise_practice_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Complete the short review exercise.",
            "Check both meaning and accuracy.",
            "Task: Compare answers with your partner.",
        ]
    )
    slide["teacher_notes"] = "Keep this part fast-paced and use it to reveal which areas still need support."
    slide["interaction_type"] = "Individual work"
    return slide


def _error_analysis_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Read the answers with mistakes.",
            "Find the problem and say why it is wrong.",
            "Task: Correct one item together.",
        ]
    )
    slide["teacher_notes"] = "Turn mistakes into learning points by asking students to explain the reason behind each correction."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _consolidation_slide(slide):
    slide["visible_content"] = _clean_lines(
        [
            "Organize today's review points in a simple chart.",
            "Choose the most useful strategy for the next test.",
            "Task: Share one key reminder with the class.",
        ]
    )
    slide["teacher_notes"] = "Use this slide to help students connect separate review points into a usable revision plan."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _summary_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            f"Today we worked on {context['topic']}.",
            "Review the key language and the main classroom task.",
            "Task: Finish the sentence 'Today I can now...'",
        ]
    )
    slide["teacher_notes"] = "Let students summarize first, then add any missing point in one concise closing comment."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _homework_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            "Review today's key language.",
            f"Finish or improve {context['output_label']}.",
            "Task: Bring one question to the next class.",
        ]
    )
    slide["teacher_notes"] = "State the product and quality requirement clearly before students leave the classroom."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


def _blackboard_design_slide(slide):
    context = slide["_context"]
    slide["visible_content"] = _clean_lines(
        [
            context["topic"],
            "Topic -> Evidence -> Language -> Output",
            "Useful frame: I think ... because ...",
        ]
    )
    slide["teacher_notes"] = "Use this structure as the board plan so students can follow the logic of the lesson clearly."
    slide["interaction_type"] = "Teacher-student interaction"
    return slide


SLIDE_BUILDERS = {
    "cover": _cover_slide,
    "objectives": _objectives_slide,
    "lead_in": _lead_in_slide,
    "prediction": _prediction_slide,
    "fast_reading": _fast_reading_slide,
    "careful_reading": _careful_reading_slide,
    "vocabulary_focus": _vocabulary_focus_slide,
    "language_points": _language_points_slide,
    "group_discussion": _group_discussion_slide,
    "observe_discover": _observe_discover_slide,
    "grammar_rule": _grammar_rule_slide,
    "guided_practice": _guided_practice_slide,
    "controlled_practice": _controlled_practice_slide,
    "communicative_practice": _communicative_practice_slide,
    "error_correction": _error_correction_slide,
    "writing_task": _writing_task_slide,
    "structure_analysis": _structure_analysis_slide,
    "useful_expressions": _useful_expressions_slide,
    "sample_analysis": _sample_analysis_slide,
    "guided_writing": _guided_writing_slide,
    "peer_review": _peer_review_slide,
    "pre_listening": _pre_listening_slide,
    "while_listening": _while_listening_slide,
    "post_listening": _post_listening_slide,
    "speaking_task": _speaking_task_slide,
    "pair_work": _pair_work_slide,
    "key_vocabulary_review": _key_vocabulary_review_slide,
    "key_grammar_review": _key_grammar_review_slide,
    "exercise_practice": _exercise_practice_slide,
    "error_analysis": _error_analysis_slide,
    "consolidation": _consolidation_slide,
    "summary": _summary_slide,
    "homework": _homework_slide,
    "blackboard_design": _blackboard_design_slide,
}


def _apply_extra_requirement(slide):
    context = slide["_context"]
    extra = context.get("extra_requirements")
    if not extra:
        return slide
    if slide["slide_type"] in {"group_discussion", "communicative_practice", "guided_writing", "pair_work"}:
        slide["visible_content"] = _clean_lines(
            list(slide.get("visible_content", [])) + [f"Teacher focus: {extra}"]
        )
    return slide


def _generate_rule_slide_from_outline(
    lesson_request,
    teaching_design,
    slide_outline,
    regenerate=False,
):
    slide = _base_slide(lesson_request, slide_outline, teaching_design)
    builder = SLIDE_BUILDERS.get(slide["slide_type"], _summary_slide)
    slide = builder(slide)
    slide = _apply_extra_requirement(slide)
    if regenerate:
        slide["teacher_notes"] = f"{slide['teacher_notes']} Keep the activity fresh by asking for a different student example this time."
    slide.pop("_context", None)
    return slide


def generate_rule_slide_content(lesson_request, teaching_design, ppt_outline):
    """Return the local rule-based slide collection without any model call."""

    slides = [
        _generate_rule_slide_from_outline(lesson_request, teaching_design, slide_outline)
        for slide_outline in ppt_outline
    ]
    return check_schema(slides)


def _knowledge_context_block(knowledge_context):
    if not knowledge_context:
        return ""
    return "\n\n" + trim_knowledge_context_for_prompt(format_knowledge_context_for_prompt(knowledge_context), max_chars=4000)


def generate_slide_content(lesson_request, teaching_design, ppt_outline, knowledge_context=None):
    """Generate classroom-ready slide content for the full outline."""

    fallback = generate_rule_slide_content(lesson_request, teaching_design, ppt_outline)

    generated = []
    chunk_size = 4
    for start in range(0, len(ppt_outline), chunk_size):
        outline_chunk = ppt_outline[start:start + chunk_size]
        fallback_chunk = fallback[start:start + chunk_size]
        stage = f"slide_content_batch_{start // chunk_size + 1}"
        system_prompt, user_prompt = _slide_content_prompts(
            lesson_request,
            teaching_design,
            outline_chunk,
            fallback_chunk,
            knowledge_context=knowledge_context,
        )
        payload = call_agent_json(
            "slide_content_agent",
            {
                "system_prompt": system_prompt,
                "user_prompt": user_prompt,
                "task_id": lesson_request.get("task_id"),
                "stage_note": stage,
            },
            fallback_fn=lambda chunk=fallback_chunk: chunk,
        )
        generated.extend(_normalize_slide_collection(payload, fallback_chunk))
    return check_schema(generated)


def generate_single_slide_content(
    lesson_request,
    teaching_design,
    slide_outline,
    regenerate=False,
    knowledge_context=None,
):
    """Generate or regenerate a single slide from outline data."""

    fallback = _generate_rule_slide_from_outline(
        lesson_request,
        teaching_design,
        slide_outline,
        regenerate=regenerate,
    )
    system_prompt, user_prompt = _single_slide_content_prompts(
        lesson_request,
        teaching_design,
        slide_outline,
        fallback,
        regenerate=regenerate,
        knowledge_context=knowledge_context,
    )
    payload = call_agent_json(
        "slide_content_agent",
        {
            "system_prompt": system_prompt,
            "user_prompt": user_prompt,
            "task_id": lesson_request.get("task_id"),
            "stage_note": "slide_content_single",
        },
        fallback_fn=lambda: fallback,
    )
    return _normalize_single_slide(payload, fallback)


def _normalize_visible_content(value, fallback):
    if isinstance(value, list):
        cleaned = _clean_lines(value, max_items=4)
        if cleaned:
            return cleaned
    return _clean_lines(fallback, max_items=4)


def _normalize_slide_index(value, fallback):
    try:
        return int(value)
    except (TypeError, ValueError):
        return int(fallback)


def _normalize_slide(candidate, fallback):
    candidate = candidate if isinstance(candidate, dict) else {}
    normalized = {
        "slide_index": _normalize_slide_index(
            candidate.get("slide_index"),
            fallback["slide_index"],
        ),
        "slide_type": str(candidate.get("slide_type") or fallback["slide_type"]).strip(),
        "title": str(candidate.get("title") or fallback["title"]).strip(),
        "visible_content": _normalize_visible_content(
            candidate.get("visible_content"),
            fallback.get("visible_content", []),
        ),
        "teacher_notes": str(candidate.get("teacher_notes") or fallback["teacher_notes"]).strip(),
        "teaching_purpose": str(
            candidate.get("teaching_purpose") or fallback["teaching_purpose"]
        ).strip(),
        "estimated_time": str(candidate.get("estimated_time") or fallback["estimated_time"]).strip(),
        "interaction_type": str(
            candidate.get("interaction_type") or fallback["interaction_type"]
        ).strip(),
    }
    return check_schema(normalized)


def _normalize_slide_collection(payload, fallback):
    candidate_slides = payload.get("slides") if isinstance(payload, dict) else payload
    if not isinstance(candidate_slides, list):
        return fallback

    slides_by_index = {}
    for slide in candidate_slides:
        if not isinstance(slide, dict):
            continue
        try:
            slide_index = int(slide.get("slide_index"))
        except (TypeError, ValueError):
            continue
        slides_by_index[slide_index] = slide
    normalized = []
    for index, fallback_slide in enumerate(fallback, start=1):
        candidate = slides_by_index.get(fallback_slide["slide_index"])
        if candidate is None and index - 1 < len(candidate_slides):
            candidate = candidate_slides[index - 1]
        normalized.append(_normalize_slide(candidate, fallback_slide))
    return check_schema(normalized)


def _normalize_single_slide(payload, fallback):
    if isinstance(payload, dict) and isinstance(payload.get("slide"), dict):
        payload = payload["slide"]
    return _normalize_slide(payload, fallback)


def _slide_content_prompts(lesson_request, teaching_design, ppt_outline, fallback, knowledge_context=None):
    system_prompt = """
You are a senior high school English PPT slide writer.
Return JSON only.
Write concise, natural classroom English suitable for Chinese senior high school students.
"""
    user_prompt = f"""
Generate slide content for this lesson.

Lesson request:
{json.dumps(lesson_request, ensure_ascii=False, indent=2)}

Teaching design:
{json.dumps(teaching_design, ensure_ascii=False, indent=2)}

PPT outline:
{json.dumps(ppt_outline, ensure_ascii=False, indent=2)}

Rule-based draft:
{json.dumps(fallback, ensure_ascii=False, indent=2)}

{_knowledge_context_block(knowledge_context)}

Return one JSON object with a "slides" array.
Each slide must include exactly these fields:
- slide_index
- slide_type
- title
- visible_content
- teacher_notes
- teaching_purpose
- estimated_time
- interaction_type

Requirements:
- visible_content must be an array of 2 to 4 short bullet strings.
- Keep each slide task-focused and classroom-ready.
- Do not output generic placeholders like "Complete the classroom task.".
- Do not output empty "Step 1 / Step 2 / Step 3" style placeholders.
- Reading lessons must include concrete reading tasks (e.g., fast reading or careful reading actions).
- For Reading careful_reading slides, include concrete structure cues such as Problem/Solution/Result, Main idea/Details/Conclusion, or Cause/Effect.
- Writing lessons must include structure, useful expressions, and checklist-oriented task cues.
- For Writing structure/guided slides, include clear Opening/Body/Ending framework cues plus checklist hints.
- Grammar lessons must include examples, rule focus, and practice actions.
- For Grammar rule slides, include examples, explicit rule statement, practice direction, and common-mistake cues.
- teacher_notes must be practical speaking prompts for the teacher.
- interaction_type should be specific, such as Individual work, Pair work, Group discussion, or Teacher-student interaction.
- Do not add markdown or explanations.
"""
    return system_prompt.strip(), user_prompt.strip()


def _single_slide_content_prompts(
    lesson_request,
    teaching_design,
    slide_outline,
    fallback,
    regenerate=False,
    knowledge_context=None,
):
    system_prompt = """
You are a senior high school English PPT slide writer.
Return JSON only.
Write concise, natural classroom English suitable for Chinese senior high school students.
"""
    extra_instruction = (
        "Regenerate the slide with slightly fresher classroom wording while keeping the same teaching purpose."
        if regenerate
        else "Generate the slide content according to the outline."
    )
    user_prompt = f"""
Generate one slide for this lesson.

Lesson request:
{json.dumps(lesson_request, ensure_ascii=False, indent=2)}

Teaching design:
{json.dumps(teaching_design, ensure_ascii=False, indent=2)}

Slide outline:
{json.dumps(slide_outline, ensure_ascii=False, indent=2)}

Rule-based draft:
{json.dumps(fallback, ensure_ascii=False, indent=2)}

{extra_instruction}

{_knowledge_context_block(knowledge_context)}

Return one JSON object with a "slide" object.
The slide must include exactly these fields:
- slide_index
- slide_type
- title
- visible_content
- teacher_notes
- teaching_purpose
- estimated_time
- interaction_type

Requirements:
- visible_content must be an array of 2 to 4 short bullet strings.
- Keep the slide classroom-ready and easy to project.
- Do not output generic placeholders like "Complete the classroom task.".
- Do not output empty "Step 1 / Step 2 / Step 3" style placeholders.
- When slide_type is careful_reading / structure_analysis / grammar_rule, include concrete structure cues (e.g., Problem-Solution-Result, Opening-Body-Ending, Examples-Rule-Practice).
- teacher_notes should guide real teaching moves.
- Do not add markdown or explanations.
"""
    return system_prompt.strip(), user_prompt.strip()
