"""Layout template registry for PPT rendering rules.

This module centralizes template constraints so renderer and quality checker
share the same limits.
"""

TEMPLATES = {
    "cover_template": {
        "template_name": "cover_template",
        "visual_variant": "hero_title",
        "max_blocks": 3,
        "max_items_per_block": 2,
        "title_font_size": 30,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["title", "unit", "lesson_type"],
        "use_graphic": False,
        "preferred_layout": "cover_layout",
        "allow_image_placeholder": True,
        "overflow_strategy": "teacher_notes",
    },
    "objectives_cards_template": {
        "template_name": "objectives_cards_template",
        "visual_variant": "numbered_cards",
        "max_blocks": 3,
        "max_items_per_block": 2,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["objective_1", "objective_2", "objective_3"],
        "use_graphic": False,
        "preferred_layout": "objectives_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "lead_in_questions_template": {
        "template_name": "lead_in_questions_template",
        "visual_variant": "question_cards",
        "max_blocks": 3,
        "max_items_per_block": 1,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["question_1", "question_2", "pair_task"],
        "use_graphic": False,
        "preferred_layout": "leadin_question_layout",
        "allow_image_placeholder": True,
        "overflow_strategy": "teacher_notes",
    },
    "prediction_task_template": {
        "template_name": "prediction_task_template",
        "visual_variant": "three_step_flow",
        "max_blocks": 3,
        "max_items_per_block": 1,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["before", "predict", "share"],
        "use_graphic": False,
        "preferred_layout": "prediction_flow_layout",
        "allow_image_placeholder": True,
        "overflow_strategy": "teacher_notes",
    },
    "fast_reading_task_template": {
        "template_name": "fast_reading_task_template",
        "visual_variant": "task_focus_card",
        "max_blocks": 3,
        "max_items_per_block": 1,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["task_1", "task_2", "task_3"],
        "use_graphic": False,
        "preferred_layout": "reading_task_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "careful_reading_question_evidence_template": {
        "template_name": "careful_reading_question_evidence_template",
        "visual_variant": "question_evidence_columns",
        "max_blocks": 3,
        "max_items_per_block": 2,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["question", "evidence", "task"],
        "use_graphic": True,
        "preferred_layout": "reading_task_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "vocabulary_clean_cards_template": {
        "template_name": "vocabulary_clean_cards_template",
        "visual_variant": "vocabulary_cards",
        "max_blocks": 3,
        "max_items_per_block": 3,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["word", "meaning", "example"],
        "use_graphic": True,
        "preferred_layout": "vocabulary_card_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "language_point_pattern_template": {
        "template_name": "language_point_pattern_template",
        "visual_variant": "pattern_practice_blocks",
        "max_blocks": 3,
        "max_items_per_block": 1,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["pattern", "example", "practice"],
        "use_graphic": False,
        "preferred_layout": "sentence_analysis_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "discussion_task_template": {
        "template_name": "discussion_task_template",
        "visual_variant": "discussion_prompt_panel",
        "max_blocks": 3,
        "max_items_per_block": 2,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["topic", "expressions", "share_task"],
        "use_graphic": False,
        "preferred_layout": "discussion_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "summary_three_takeaways_template": {
        "template_name": "summary_three_takeaways_template",
        "visual_variant": "three_takeaway_cards",
        "max_blocks": 3,
        "max_items_per_block": 1,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["what_we_learned", "how_we_read", "what_we_can_say"],
        "use_graphic": True,
        "preferred_layout": "mindmap_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "homework_task_template": {
        "template_name": "homework_task_template",
        "visual_variant": "homework_levels",
        "max_blocks": 3,
        "max_items_per_block": 1,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["basic", "optional", "challenge"],
        "use_graphic": False,
        "preferred_layout": "homework_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
    "blackboard_structure_template": {
        "template_name": "blackboard_structure_template",
        "visual_variant": "board_structure",
        "max_blocks": 3,
        "max_items_per_block": 2,
        "title_font_size": 24,
        "body_font_size": 18,
        "label_font_size": 14,
        "min_font_size": 14,
        "content_priority": ["topic", "key_words", "structure"],
        "use_graphic": False,
        "preferred_layout": "blackboard_layout",
        "allow_image_placeholder": False,
        "overflow_strategy": "teacher_notes",
    },
}


SLIDE_TEMPLATE_MAP = {
    "cover": "cover_template",
    "objectives": "objectives_cards_template",
    "lead_in": "lead_in_questions_template",
    "prediction": "prediction_task_template",
    "pre_reading": "prediction_task_template",
    "fast_reading": "fast_reading_task_template",
    "careful_reading": "careful_reading_question_evidence_template",
    "vocabulary_focus": "vocabulary_clean_cards_template",
    "language_points": "language_point_pattern_template",
    "group_discussion": "discussion_task_template",
    "summary": "summary_three_takeaways_template",
    "homework": "homework_task_template",
    "blackboard_design": "blackboard_structure_template",
}


def get_template(name):
    return dict(TEMPLATES.get(name) or {})


def get_template_for_slide(slide_type):
    return get_template(SLIDE_TEMPLATE_MAP.get(str(slide_type or "").strip(), ""))
